/**
 * Placeholder ligero para imágenes que llegan por URL desde la base de datos.
 * Next puede desenfocarlo y reemplazarlo de forma nativa cuando termina de
 * descargar la imagen real, sin JavaScript ni una segunda petición.
 */
export const IMAGE_BLUR_DATA_URL =
  "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAzMiI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJnIiB4MT0iMCIgeTE9IjAiIHgyPSIxIiB5Mj0iMSI+PHN0b3Agc3RvcC1jb2xvcj0iJTIzZDlkNmNlIi8+PHN0b3Agb2Zmc2V0PSIuNSIgc3RvcC1jb2xvcj0iJTIzYWFhNjlmIi8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIlMjM3NDZmNjkiLz48L2xpbmVhckdyYWRpZW50PjxmaWx0ZXIgaWQ9ImIiPjxmZUdhdXNzaWFuQmx1ciBzdGREZXZpYXRpb249IjIuNSIvPjwvZmlsdGVyPjwvZGVmcz48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMzIiIGZpbGw9InVybCglMjNnKSIvPjxjaXJjbGUgY3g9IjUiIGN5PSI5IiByPSI4IiBmaWxsPSIlMjNkMGE1OTciIGZpbHRlcj0idXJsKCUyM2IpIi8+PGNpcmNsZSBjeD0iMjAiIGN5PSIyNSIgcj0iOSIgZmlsbD0iJTIzNGU1YzU0IiBmaWx0ZXI9InVybCglMjNiKSIvPjwvc3ZnPg==";
